'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Save } from 'lucide-react';
import { createClient } from '@/lib/supabase';

export default function SettingsPage() {
  const [timezone, setTimezone] = useState('Asia/Kolkata'); const [time, setTime] = useState('19:00'); const [timer, setTimer] = useState(15); const [maintenance, setMaintenance] = useState(false); const [automation, setAutomation] = useState(false); const [library, setLibrary] = useState(false); const [message, setMessage] = useState(''); const s = createClient();
  useEffect(() => { if (!s) return; s.from('app_settings').select('key,value').in('key', ['publishing', 'quiz', 'maintenance', 'automation', 'daily_content_library']).then(({ data }) => { const x = Object.fromEntries((data || []).map((v: { key: string; value: Record<string, unknown> }) => [v.key, v.value])); setTimezone(String(x.publishing?.timezone || 'Asia/Kolkata')); setTime(String(x.publishing?.chronicles_time || '19:00')); setTimer(Number(x.quiz?.timer_seconds || 15)); setMaintenance(Boolean(x.maintenance?.enabled)); setAutomation(Boolean(x.automation?.enabled)); setLibrary(Boolean(x.daily_content_library?.enabled)); }); }, []);
  async function save() { if (!s) return; const { error } = await s.from('app_settings').upsert([{ key: 'publishing', value: { timezone, chronicles_time: time, news_target_per_day: 2, incident_daily_limit: 3 } }, { key: 'quiz', value: { timer_seconds: timer, correct_points: 10, wrong_points: -5, questions_per_day: 3, streak_bonus_points: 0 } }, { key: 'maintenance', value: { enabled: maintenance } }, { key: 'automation', value: { enabled: automation, incident_review_minutes: 60, require_verified_sources: true } }, { key: 'daily_content_library', value: { enabled: library, start_date: '2026-09-01', days: 90 } }]); setMessage(error ? error.message : 'Settings saved. Daily publishing will run each morning when both automation switches are on.'); }
  return <main className="page"><Link href="/admin" className="mb-6 inline-flex items-center gap-2 text-sm text-[#AFC3D6]"><ArrowLeft size={16} /> Dashboard</Link><p className="eyebrow">Control tower</p><h1 className="mt-1 text-3xl font-bold">Settings</h1>{message && <p className="mt-4 rounded-xl bg-sky/10 p-3 text-sm text-sky">{message}</p>}<section className="card mt-6 space-y-5 p-5"><label className="block text-xs text-[#AFC3D6]">TIMEZONE<input value={timezone} onChange={e => setTimezone(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-ink p-3 text-sm" /></label><label className="block text-xs text-[#AFC3D6]">CHRONICLES TIME<input type="time" value={time} onChange={e => setTime(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-ink p-3 text-sm" /></label><label className="block text-xs text-[#AFC3D6]">QUIZ TIMER<input type="number" value={timer} onChange={e => setTimer(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-line bg-ink p-3 text-sm" /></label><label className="flex items-center justify-between rounded-xl border border-sky/40 p-4 text-sm"><span><b>Automatic daily publisher</b><small className="mt-1 block text-xs text-[#91A9C2]">Creates 3 quiz questions and the day’s Fact or Story from the free 90-day library.</small></span><input type="checkbox" checked={library} onChange={e => setLibrary(e.target.checked)} className="h-5 w-5 accent-[#60B7FF]" /></label><label className="flex items-center justify-between rounded-xl border border-line p-4 text-sm"><span><b>News automation</b><small className="mt-1 block text-xs text-[#91A9C2]">Runs the official-source incident review queue. You can publish extra news manually.</small></span><input type="checkbox" checked={automation} onChange={e => setAutomation(e.target.checked)} className="h-5 w-5 accent-[#60B7FF]" /></label><label className="flex items-center justify-between rounded-xl border border-amber/40 p-4 text-sm"><span><b>Maintenance mode</b><small className="mt-1 block text-xs text-[#91A9C2]">Home page displays the upgrade message.</small></span><input type="checkbox" checked={maintenance} onChange={e => setMaintenance(e.target.checked)} className="h-5 w-5 accent-[#FFB84D]" /></label><button onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl bg-sky py-3 text-sm font-bold text-ink"><Save size={16} /> Save settings</button></section></main>;
}
